using UnityEngine;

public class InternalDB : MonoBehaviour
{
	public void populateDB()
	{
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 1, textSwe = "Hoppa hopprep.", textEng = "Skip ropes.", costs = false, outside = true, winter = false, material = true, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 2, textSwe = "Gå till stranden.", textEng = "Go to the beach.", costs = false, outside = true, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 3, textSwe = "Baka tillsammans.", textEng = "Bake something together. ", costs = false, outside = false, winter = false, material = true, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 4, textSwe = "Blås såpbubblor.", textEng = "Blow bubbles.", costs = false, outside = true, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 5, textSwe = "Lägg fram tio olika föremål. Alla blundar och ett föremål tas bort. Vilket föremål fattas?", textEng = "Put ten different objects in front of your kids. Tell them to close their eyes. Remove one object. Which one is missing?", costs = false, outside = false, winter = false, material = false, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 6, textSwe = "Åk till ett nöjesfält eller ett tivoli. ", textEng = "Go to an amusement park. ", costs = true, outside = true, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 7, textSwe = "Åk till en djurpark.", textEng = "Visit a zoo.", costs = true, outside = true, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 8, textSwe = "Flyga drake.", textEng = "Fly a kite!", costs = false, outside = true, winter = false, material = true, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 9, textSwe = "Ta en cykeltur tillsammans.", textEng = "Go for a bike ride together.", costs = false, outside = true, winter = false, material = true, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 10, textSwe = "Vattenkrig!", textEng = "Waterfight!", costs = false, outside = true, winter = false, material = true, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 11, textSwe = "Ha en picknick.", textEng = "Picnic time! ", costs = false, outside = true, winter = false, material = true, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 12, textSwe = "Hitta tre stenar, två gula blommor och en pinne som är ungefär tio centimeter lång. ", textEng = "Find three different stones, two yellow flowers and a stick that is approximately ten centimeters long. ", costs = false, outside = true, winter = false, material = false, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 13, textSwe = "Hitta fyra saker som är ungefär tio centimeter långa. ", textEng = "Look for four different objects that are approximately ten centimeters long. ", costs = false, outside = false, winter = false, material = false, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 14, textSwe = "Plocka olika sorters löv och gör en tavla. ", textEng = "Pick different kinds of leafs and make a collage. ", costs = false, outside = true, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 15, textSwe = "Gå till stranden och plocka fina stenar.", textEng = "Go to the beach and find pretty rocks.", costs = false, outside = true, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 16, textSwe = "Upptäck världen med Google Maps - leta efter barnens skola, landstället eller varför inte Disneyland i Paris?", textEng = "Discover the world with Google Maps - look for the kids´school, your summer house or why not tune in to Disneyland in Paris?", costs = false, outside = false, winter = false, material = false, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 17, textSwe = "Åk till badhuset. ", textEng = "Visit an indoor swimming pool.", costs = true, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 18, textSwe = "Gå på upptäcktsfärd med ett förstoringsglas. Dokumentera det ni hittar med kamera och gör ett kollage. ", textEng = "Discover your surrounding with a magnifying glass. Document your finds with a camera and make a collage!", costs = false, outside = false, winter = false, material = true, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 19, textSwe = "Gå till biblioteket.", textEng = "Go to the library.", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 20, textSwe = "Gör en skattkarta och gå på skattjakt!", textEng = "Create a treasure map and go hunting!", costs = false, outside = false, winter = false, material = true, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 21, textSwe = "Gå till skogen och gör kottdjur av kottar.", textEng = "Go to the woods and make animals out of pinecones.", costs = false, outside = true, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 22, textSwe = "Leta efter sju olika sorters blommor. ", textEng = "Look for seven different types of flowers. ", costs = false, outside = true, winter = false, material = false, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 23, textSwe = "Skriv en vårdikt. ", textEng = "Write a poem about spring.", costs = false, outside = false, winter = true, material = true, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 24, textSwe = "Lär er alfabetet på teckenspråk.", textEng = "Learn your ABCs in sign language. ", costs = false, outside = false, winter = false, material = false, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 25, textSwe = "Återskapa en känd målning. ", textEng = "Recreate a famous painting.", costs = false, outside = false, winter = false, material = true, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 26, textSwe = "Skapa ett familjeträd.", textEng = "Create a family tree.", costs = false, outside = false, winter = false, material = true, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 27, textSwe = "Gör en låtsastidning!", textEng = "Create a make belive news paper. ", costs = false, outside = false, winter = false, material = true, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 28, textSwe = "Hitta på en sång om familjen!", textEng = "Make up a song about your family members. ", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 29, textSwe = "Husdjur? Dags för ett bad kanske!", textEng = "Pets? Maybe time for a bath?", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 30, textSwe = "Ta roliga snapchatbilder och skicka till människor ni känner!", textEng = "Take funny snapchat pictures and send to people you know!", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 31, textSwe = "Inga pärlor hemma? Gör halsband av pasta!", textEng = "No beads at home? Make jewelry out pasta!", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 32, textSwe = "Gamla lådor liggandes hemma? Med lite fantasi och lite färg eller omslagspapper blir en låda lätt en rolig aktivitet att sysselsätta sig med. Lådtåg? Dockhus? Eller en skattkista kanske?", textEng = "Make something out of an old box! Maybe a train? Or why not a house?", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 33, textSwe = "Gör ett spindelnät av tejp och kasta saker på det för att se om det fastnar! Övar motorik samtidigt som det är kul!", textEng = "Make a spider web out of cellotape and throw things at it!", costs = false, outside = false, winter = false, material = false, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 34, textSwe = "Baka lussebullar.", textEng = "Make saffron buns!", costs = false, outside = false, winter = false, material = true, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 35, textSwe = "Gör chokladbollar.", textEng = "Make chocolate balls. ", costs = false, outside = false, winter = false, material = true, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 36, textSwe = "Baka olika sorters småkakakor.", textEng = "Bake coockies!", costs = false, outside = false, winter = false, material = true, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 37, textSwe = "Baka kanelbullar.", textEng = "Make cinnamon buns.", costs = false, outside = false, winter = false, material = true, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 38, textSwe = "Baka pepparkakor.", textEng = "Make gingerbread cookies!", costs = false, outside = false, winter = false, material = true, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 39, textSwe = "Gör cupcakes.", textEng = "Bake some cupcakes!", costs = false, outside = false, winter = false, material = true, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 40, textSwe = "Gör egna badbomber - googla för recept! ", textEng = "Make your own bath bombs - google for recipe!", costs = false, outside = false, winter = false, material = true, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 41, textSwe = "Arrangera en biokväll för familjen med popcorn och film!", textEng = "Arrange a movie night with popcorn and a good movie!", costs = false, outside = false, winter = false, material = true, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 42, textSwe = "Gå till parken.", textEng = "Go to the park. ", costs = false, outside = true, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 43, textSwe = "Har barnen en favoritbok? Gör en pjäs av den!", textEng = "Act out the children's favourite book! ", costs = false, outside = false, winter = false, material = false, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 44, textSwe = "Gör en hinderbana av kuddar, leksaker eller det ni har hemma!", textEng = "Make an obstacle course out of pillows! ", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 45, textSwe = "Pyssla med pärlor.", textEng = "+Craft with beads!", costs = false, outside = false, winter = false, material = true, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 46, textSwe = "Lägg pärlplattor.", textEng = "+Play with pegboards!", costs = false, outside = false, winter = false, material = true, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 47, textSwe = "Bada bubbelbad!", textEng = "Take a bubblebath!", costs = false, outside = false, winter = false, material = true, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 48, textSwe = "Lek med vatten! Ta fram bunkar, glas och skålor och lek på! ", textEng = "Play with water!", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 49, textSwe = "Gör en egen musikvideo.", textEng = "Create your own music video.", costs = false, outside = false, winter = false, material = true, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 50, textSwe = "Gör ett kollage av gamla tidningar.", textEng = "Create a collage out of old newspapers and magazines. ", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 51, textSwe = "Läs en bok.", textEng = "Read a book.", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 52, textSwe = "Rita av varandra. ", textEng = "Draw each other.", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 53, textSwe = "Rita en tavla tillsammans. ", textEng = "Paint together.", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 54, textSwe = "Discodags!", textEng = "Disco time!", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 55, textSwe = "Rensa ett skåp eller en låda och donera saker ni inte behöver eller vill ha. ", textEng = "Clear out a drawer and donate things you don't need or want. ", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 56, textSwe = "Städa barnens rum - gör det till en lek!", textEng = "Clean the kids' room - make a game out of it!", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 57, textSwe = "Se på film!", textEng = "Watch a movie!", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 58, textSwe = "Gör ett eget korsord och lös det tillsammans.", textEng = "Make your own crossword puzzle and solve it together. ", costs = false, outside = false, winter = false, material = false, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 59, textSwe = "Lös korsord - det går att hitta gratis om man googlar!", textEng = "Solve crossword puzzles - you can find a bunch of them free online!", costs = false, outside = false, winter = false, material = false, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 60, textSwe = "Skriv ett brev till någon ni känner.", textEng = "Write a letter to someone you know. ", costs = false, outside = false, winter = false, material = false, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 61, textSwe = "Lek kurragömma!", textEng = "Play hide and seek!", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 62, textSwe = "Klä ut er!", textEng = "Play dress up!", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 63, textSwe = "Titta på familjebilder tillsammans.", textEng = "Look at family pictures together. ", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 64, textSwe = "Gör en scrapbook med bilder på familjen.", textEng = "Make a scrapbook! ", costs = true, outside = false, winter = false, material = true, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 65, textSwe = "Busring till någon ni känner!", textEng = "Make a prank call to someone you know!", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 66, textSwe = "Gör trolldeg i olika färger. ", textEng = "Make your own playdough!", costs = false, outside = false, winter = false, material = true, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 67, textSwe = "Julpyssla!", textEng = "Make Christmas decorations!", costs = false, outside = false, winter = true, material = true, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 68, textSwe = "Påskpyssla!", textEng = "Make Easter decorations!", costs = false, outside = false, winter = false, material = true, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 69, textSwe = "Spela ett roligt brädspel!", textEng = "Play boardgames together! ", costs = false, outside = false, winter = false, material = false, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 70, textSwe = "Gå på loppis och leta efter något ni kan göra tillsammans. Kanske hittar ni något roligt spel?", textEng = "+Go thrifting.", costs = true, outside = true, winter = false, material = false, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 71, textSwe = "Gå ut och leta efter hösttecken!", textEng = "Go out and look for signs of fall.", costs = false, outside = true, winter = false, material = false, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 72, textSwe = "Gå ut och leta efter vårtecken! ", textEng = "Go out and look for signs of spring.", costs = false, outside = true, winter = true, material = false, pedagogic = true});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 73, textSwe = "Åk pulka!", textEng = "Go sledding!", costs = false, outside = true, winter = true, material = true, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 74, textSwe = "Åk skridskor! ", textEng = "Go ice skiing!", costs = false, outside = true, winter = true, material = true, pedagogic = false});
		this.gameObject.transform.GetComponent<DatabaseHandler>().testList.Add(new Item {id = 75, textSwe = "Rensa bland barnens kläder och donera eller lägg undan det som inte passar. ", textEng = "Clear out the childrens' wardrobe and donate things you don't want or need. ", costs = false, outside = false, winter = false, material = false, pedagogic = false});
		
	}
}